### ISSUE TITLE
Now that React 16 has been released can we release a new version of sablono?

### ISSUE THREAD

**Issue by bhauman** [r0man/sablono#178]
React 16 needs the changes you introduced here: https://github.com/r0man/sablono/commit/fb5d756c4201598fe8737ae2877e76f9c25a96f1

I'd like to cut a new release of devcards that React 16 compliant, but I'm blocking on the release of 0.8.1.

Thanks for such a great lib!!

**Comment by r0man** [comment]
@bhauman I haven't looked into React 16 yet. I'm a bit busy at the moment. Would a release of the latest master help you moving forward? Did you test sablono already with React 16?
Also, thanks for Figwheel!

**Comment by bhauman** [comment]
Yes the latest master appears to work well with React 16. I'm currently using the snapshot.

And you're welcome!

**Comment by r0man** [comment]
@bhauman I just released `0.8.1` of sablono. I will look into React 16 when I have a bit more time.

**Comment by bhauman** [comment]
Thanks!!

**Comment by DjebbZ** [comment]
Bumping the issue : is someone working on it ? I'd like to help, my current employer is willing to give some time to help pushing the effort forward. We'd love to upgrade our app to React 16 (we're using rum). But for this I need guidance :
- What prevents Sablono to be compatible with React 16 ?
- What needs to be worked on ?
- How to follow the code of Sablono ?

The more precise the answer the better. I'd love to have a clear picture of what's needed to move forward.

**Comment by r0man** [comment]
@DjebbZ I looked into this a bit a couple of weeks ago, but got biten a bit, because the sablono test suite depends on other projects like om, rum and regaent. Because of that I run into dependency issues just updating the cljsjs version, which  usually works. I tried using the new npm-deps, but also remember strange things. I got the test suite running under nodejs, but completly failing on phantomjs. I just didn't had time to dig any deeper, and decided to wait a bit. :)

So the main blocker at the moment are those dependency issues. I think the best way moving forward is to temporarly disable the tests that depend on the other libraries, then get the sablono test suite running via npm-deps, and finally find a way to enable those tests again.

**Comment by DjebbZ** [comment]
Thanks for the pointers. Just so you know, I'll be tackling first porting [rum itself to React 16](https://github.com/tonsky/rum/pull/151#issuecomment-353131839), then I'll come back here.

**Comment by DjebbZ** [comment]
If you read the other issue, it appears @piranha already did most of the job for rum. Gonna work on Sablono.

**Comment by DjebbZ** [comment]
Report so far : big troubles launching a REPL connected to a javascript environment. I managed to get something with `lein figwheel devcards`. I don't understand how Leiningen works. Can you help me launching a REPL connected to Nashorn ? and PhantomJS ?

Running `lein ci` show that almost all test with Nashorn and PhantomJS fail because anytime you have some content in a html tag like `[:div "some content"]` the data structure returned has an unecessary attribute `:children` with the content in it. Doesn't happen in Nodejs nor the browser (as proved with the Figwheel REPL).

Will continue to dig more into it and report stuff.

**Comment by DjebbZ** [comment]
I've miserably failed to launch a Nashorn repl : `lein repl` in sablono then :

```
user=> (require '[cljs.repl :as repl])
nil
user=> (require '[cljs.repl.nashorn :as nashorn])
nil
user=> (repl/repl (nashorn/repl-env))
To quit, type: :cljs/quit
cljs.user=> (require '[sablono.test :as st])               
TypeError: Cannot load script from .cljs_nashorn_repl/goog/undefined
	 (NO_SOURCE_FILE <eval>:1:0)
	 (NO_SOURCE_FILE <eval>:1:0)
	 (NO_SOURCE_FILE <eval>:19:0)
	 <program> (.cljs_nashorn_repl/tubax/core.cljs:4:0)
	 (NO_SOURCE_FILE <eval>:1:0)
	 (NO_SOURCE_FILE <eval>:1:0)
	 (NO_SOURCE_FILE <eval>:19:0)
	 <program> (.cljs_nashorn_repl/sablono/test.cljs:6:0)
	 (NO_SOURCE_FILE <eval>:1:0)
	 (NO_SOURCE_FILE <eval>:1:0)
	 (NO_SOURCE_FILE <eval>:19:0)
	 (NO_SOURCE_FILE <eval>:1:0)
```

Mmmh... Maybe refer the macros ?

```
cljs.user=> (require '[sablono.test :refer-macros [html-data html-str]])

cljs.user=> (html-data [:div])
WARNING: Use of undeclared Var sablono.core/create-element at line 1 <cljs repl>
TypeError: Cannot read property "render_static" from undefined
	 (NO_SOURCE_FILE <eval>:1:0)
	 (NO_SOURCE_FILE <eval>:1:0)
	 (NO_SOURCE_FILE <eval>:1:0)
	 (NO_SOURCE_FILE <eval>:1:0)
```

Looks like I need to require sablono.core

```
cljs.user=> (require 'sablono.core)
clojure.lang.ExceptionInfo: Invalid :refer, var module$home$djebbz$code$etc$sablono$node-modules$react$index/createElement does not exist in file /home/djebbz/code/etc/sablono/src/sablono/interpreter.cljc {:tag :cljs/analysis-error}
... ;; LONG STACKTRACE
```

After several attempts to use Nashorn's `load` function to load React from `node_modules/react/index.js` or `.cljs_nashorn_repl/node_modules/react/index.js`, I still fail to have anything working.

I'd love some help. Otherwise I can't fix tests, so I can't help at all.

**Comment by r0man** [comment]
@DjebbZ No idea how to get the nashorn REPL running. It doesn't work on my machine with cider. However, I got a bit further with React 16 in this branch: 

https://github.com/r0man/sablono/tree/react-16

I think the problems with phantomjs and nashorn are because they need a polyfill for some newer JavaScript features. But not sure.

**Comment by DjebbZ** [comment]
Actually I was trying to fix things in branch `npm-16`, which is 1 commit ahead of `react-16` and makes use of the new `:npm-deps` feature of CLJS. Maybe I should try without this.

**Comment by r0man** [comment]
I think we have this now ...
