### ISSUE TITLE
transferPropsTo is now deprecated in React

### ISSUE THREAD

**Issue by tonsky** [r0man/sablono#47]
Hi!

`transferPropsTo` is now deprecated in React: https://gist.github.com/sebmarkbage/a6e220b7097eb3c79ab7

It’s used in `interpreter/wrap-form-element`
https://github.com/r0man/sablono/blob/master/src/sablono/interpreter.cljx#L35

It generates warning every time form element is used:

> Warning: transferPropsTo is deprecated. See http://fb.me/react-transferpropsto for more information.

BTW may I ask, what is the motivation behind wrapping React input elements with wrapper? Why don’t just use raw React inputs?

**Comment by r0man** [comment]
Hi tonsky,

thanks, I'll update this in the next days. The reason input
elements are wrapped is because there were problems with the
cursor in input elements beeing reseted when typing. This fix, is
actually copied from om, and the original issue is here:

https://github.com/r0man/sablono/issues/10

Roman.

**Comment by r0man** [comment]
@tonsky This should be fixed in `0.3.0-SNAPSHOT`. Can you verify this is working for you?

**Comment by tonsky** [comment]
Confirm — all works, warnings are gone, thanks!=
