### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by tonsky** [r0man/sablono#93]
Hi!

I’m interested in what have changed between 0.4.0 and 0.5.3?

Also, any chance we can have a changelog published somewhere?

Thanks!

**Comment by r0man** [comment]
Hey @tonsky,

there shouldn't be any user facing changes. Previously macros
were expanded via Clojure's macroexpand when compiling. This is
obviosuly wrong because the code returned by Clojure's
macroexpand is not necesarrily valid ClojureScript code. Here's
the change:

https://github.com/r0man/sablono/commit/6b23da66d4a3d92a5b002ccb3ea430247ec3cbf3#diff-e82cddb7f41c5234ec4cf440d61bbf88L131

Apart from that I switched to lein-doo for the tests and did some
refactoring. I'll try to maintain a Changelog in the future ;)

Roman

**Comment by tonsky** [comment]
Thanks for the explanation!

Is cljsjs/react-dom-server a must-have dependency now?

**Comment by r0man** [comment]
No, only if you do server side rendering, like render-string or
render-static.

**Comment by r0man** [comment]
@tonsky & @niwinz Sorry, I think react-dom-server is required as a dependency because of this line here: https://github.com/r0man/sablono/blob/master/src/sablono/core.cljs#L11
I haven't tested it, but I think you will get a compiler error. Also not tested, but I would expect advanced mode to get rid of the dom server dependency, provided you don't use render-string or render-static.

**Comment by niwinz** [comment]
I get a compile error without -server dependency, so I confirm that is required.

**Comment by tonsky** [comment]
@r0man no, it does not get rid of it. Minified JS are not subject to Google Closure compiler optimizations, they’re just copied as-is.

@r0man how important do you think is to keep these two functions? It will force every client-side app that uses Sablono to have server-rendering code baked into minified JS. For me this is a counter-productive: client apps should not have server-rendering code, that was one of the reasons why React was split into smaller projects.

Possible solutions: 

- remove require. Using `render` or `render-static` will cause runtime error without including `react-dom-server`
- create separate `sablono-server` lib that will contain these two fns only (imho overkill)
- remove `render` or `render-static`, let users implement them on their own. Should be ok given how trivial these functions are

**Comment by r0man** [comment]
I think you are right, and I think I would prefer option 3, removing those
functions. I'm in Sri Lanka at the moment and AFK for the next 4 weeks.
I'll take a look at this when I am back.

**Comment by tonsky** [comment]
Great! Thank you

**Comment by niwinz** [comment]
It there also an other option I think, declare that functions in separate namespace and require react-dom-server on it and declare the react-dom-server dependency as provided. So if the user requires that namespace, the user will be the responsable to include the react-dom-server dependency.

This works perfectly in clojure, can it work in same way with clojurescript?

**Comment by r0man** [comment]
Closing this. I added a changelog. I added an issue for the server rendering namespace over here https://github.com/r0man/sablono/issues/100
